// Code generated by go-enum DO NOT EDIT.
// Version: 0.3.11
// Revision: e477e74e05be2411bb0b218a4637de6905e8cd8c
// Build Date: 2022-02-11T00:05:30Z
// Built By: goreleaser

package enums

import (
	"fmt"
	"strings"
)

const (
	// CurrencyUnknow is a Currency of type Unknow.
	CurrencyUnknow Currency = iota
	// CurrencyUSD is a Currency of type USD.
	CurrencyUSD
	// CurrencyRUB is a Currency of type RUB.
	CurrencyRUB
	// CurrencyEUR is a Currency of type EUR.
	CurrencyEUR
)

const _CurrencyName = "UnknowUSDRUBEUR"

var _CurrencyNames = []string{
	_CurrencyName[0:6],
	_CurrencyName[6:9],
	_CurrencyName[9:12],
	_CurrencyName[12:15],
}

// CurrencyNames returns a list of possible string values of Currency.
func CurrencyNames() []string {
	tmp := make([]string, len(_CurrencyNames))
	copy(tmp, _CurrencyNames)
	return tmp
}

var _CurrencyMap = map[Currency]string{
	CurrencyUnknow: _CurrencyName[0:6],
	CurrencyUSD:    _CurrencyName[6:9],
	CurrencyRUB:    _CurrencyName[9:12],
	CurrencyEUR:    _CurrencyName[12:15],
}

// String implements the Stringer interface.
func (x Currency) String() string {
	if str, ok := _CurrencyMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Currency(%d)", x)
}

var _CurrencyValue = map[string]Currency{
	_CurrencyName[0:6]:                    CurrencyUnknow,
	strings.ToLower(_CurrencyName[0:6]):   CurrencyUnknow,
	_CurrencyName[6:9]:                    CurrencyUSD,
	strings.ToLower(_CurrencyName[6:9]):   CurrencyUSD,
	_CurrencyName[9:12]:                   CurrencyRUB,
	strings.ToLower(_CurrencyName[9:12]):  CurrencyRUB,
	_CurrencyName[12:15]:                  CurrencyEUR,
	strings.ToLower(_CurrencyName[12:15]): CurrencyEUR,
}

// ParseCurrency attempts to convert a string to a Currency.
func ParseCurrency(name string) (Currency, error) {
	if x, ok := _CurrencyValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _CurrencyValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Currency(0), fmt.Errorf("%s is not a valid Currency, try [%s]", name, strings.Join(_CurrencyNames, ", "))
}

func (x Currency) Ptr() *Currency {
	return &x
}

// MarshalText implements the text marshaller method.
func (x Currency) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Currency) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCurrency(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
